import React, { useState, useEffect } from 'react';
import { Sidebar } from './components/Sidebar';
import { BotGhostPromptHeader } from './components/BotGhostPromptHeader';
import { DiscordChatPlayground } from './components/DiscordChatPlayground';
import { BotStudioModules } from './components/BotStudioModules';
import { LiveBotHostingDashboard } from './components/LiveBotHostingDashboard';
import { LiveGatewayView } from './components/LiveGatewayView';
import { SchedulersView } from './components/SchedulersView';
import { TwoFactorSecurityView } from './components/TwoFactorSecurityView';
import { AIAssistantPanel } from './components/AIAssistantPanel';
import { WelcomeAuthScreen } from './components/WelcomeAuthScreen';
import { AccountSettingsView } from './components/AccountSettingsView';
import { AIBuildingView } from './components/AIBuildingView';
import { AdminPanel } from './components/AdminPanel';
import { TokenModal } from './components/TokenModal';
import { IdeasRouletteModal } from './components/IdeasRouletteModal';
import { GitHubGuideModal } from './components/GitHubGuideModal';
import { SecurityModal } from './components/SecurityModal';
import { AuthModal } from './components/AuthModal';
import { generateBotFromPrompt, BOT_IDEA_LIBRARY } from './utils/botGeneratorEngine';
import { BotProject, BotTokenInfo, MainAppViewMode, TwoFactorSecurityData } from './types';
import { auth, signInWithGoogle, signUpWithEmail, signInWithEmail, logOut, NovaForgeUser } from './lib/firebase';
import { onAuthStateChanged } from 'firebase/auth';
import { startTelemetryHeartbeat, trackTelemetryEvent } from './lib/telemetryService';
import { 
  saveUserBotData, 
  loadUserBotData, 
  saveGuestBotData, 
  loadGuestBotData, 
  exportCredentialsTxt, 
  loadTwoFactorData, 
  saveTwoFactorData 
} from './lib/userDataService';
import { 
  Sparkles, 
  MessageSquare, 
  Cpu, 
  Radio, 
  Layers, 
  Zap, 
  ShieldCheck, 
  Lock, 
  CheckCircle2, 
  Cloud, 
  Download, 
  Menu, 
  Key, 
  CalendarClock, 
  Smartphone, 
  User, 
  ChevronRight,
  ExternalLink
} from 'lucide-react';

export default function App() {
  const [prompt, setPrompt] = useState('Build an all-in-one NovaForge bot with /help, /daily coins, /shop, /dungeon, /ticket support, and auto-mod protection');
  const [isGenerating, setIsGenerating] = useState(false);
  const [isTokenModalOpen, setIsTokenModalOpen] = useState(false);
  const [isIdeasModalOpen, setIsIdeasModalOpen] = useState(false);
  const [isGuideOpen, setIsGuideOpen] = useState(false);
  const [isSecurityModalOpen, setIsSecurityModalOpen] = useState(false);
  const [isAuthModalOpen, setIsAuthModalOpen] = useState(false);
  const [isAIAssistantOpen, setIsAIAssistantOpen] = useState(false);
  
  // Side Panel Navigation State
  const [isSidebarCollapsed, setIsSidebarCollapsed] = useState(false);
  const [isMobileSidebarOpen, setIsMobileSidebarOpen] = useState(false);

  // 2FA Security State
  const [twoFactorData, setTwoFactorData] = useState<TwoFactorSecurityData>(() => loadTwoFactorData());

  // Default to 'welcome_auth' on initial first load unless user already visited, or direct navigation to /admin/panel
  const [mainViewMode, setMainViewMode] = useState<MainAppViewMode>(() => {
    try {
      const path = window.location.pathname.toLowerCase();
      const hash = window.location.hash.toLowerCase();
      if (path.includes('/admin') || hash.includes('admin')) {
        return 'admin_panel';
      }
      const hasVisited = localStorage.getItem('novaforge_has_visited');
      if (hasVisited === 'true') {
        return 'dash';
      }
    } catch {
      // ignore
    }
    return 'welcome_auth';
  });

  // NovaForge Auth State
  const [currentUser, setCurrentUser] = useState<NovaForgeUser | null>(() => {
    try {
      const cached = localStorage.getItem('novaforge_active_user');
      if (cached) return JSON.parse(cached);
    } catch {
      // ignore
    }
    return null;
  });
  const [isAuthLoading, setIsAuthLoading] = useState<boolean>(false);
  const [isCloudSyncing, setIsCloudSyncing] = useState<boolean>(false);

  // Bot Token & Verified Info
  const [token, setToken] = useState('');
  const [tokenInfo, setTokenInfo] = useState<BotTokenInfo | null>(null);
  const [isValidatingToken, setIsValidatingToken] = useState(false);

  // Active Bot Project (Generated by Engine or loaded from cache)
  const [botProject, setBotProject] = useState<BotProject>(() => {
    const guestData = loadGuestBotData();
    if (guestData?.project && Array.isArray(guestData.project.commands) && guestData.project.commands.length > 0) {
      return guestData.project;
    }
    return generateBotFromPrompt('Build an all-in-one NovaForge bot with /help, /daily coins, /shop, /dungeon, /ticket support, and auto-mod protection');
  });

  // Keep URL in sync with view mode and track telemetry
  useEffect(() => {
    const handleLocationChange = () => {
      const path = window.location.pathname.toLowerCase();
      const hash = window.location.hash.toLowerCase();
      if (path.includes('/admin') || hash.includes('admin')) {
        setMainViewMode('admin_panel');
      }
    };

    window.addEventListener('popstate', handleLocationChange);
    window.addEventListener('hashchange', handleLocationChange);
    return () => {
      window.removeEventListener('popstate', handleLocationChange);
      window.removeEventListener('hashchange', handleLocationChange);
    };
  }, []);

  // Update browser URL on view changes
  useEffect(() => {
    if (mainViewMode === 'admin_panel') {
      if (!window.location.pathname.includes('/admin')) {
        window.history.pushState(null, '', '/admin/panel');
      }
    } else if (window.location.pathname.includes('/admin')) {
      window.history.pushState(null, '', '/');
    }

    if (mainViewMode !== 'welcome_auth') {
      try {
        localStorage.setItem('novaforge_has_visited', 'true');
      } catch {
        // ignore
      }
    }

    trackTelemetryEvent({
      type: 'PAGE_VIEW',
      userId: currentUser?.uid,
      userEmail: currentUser?.email,
      userName: currentUser?.displayName,
      details: { viewMode: mainViewMode }
    });
  }, [mainViewMode, currentUser]);

  // Start telemetry heartbeat pulse
  useEffect(() => {
    startTelemetryHeartbeat(currentUser);
  }, [currentUser]);

  // Restore guest token if available on first mount
  useEffect(() => {
    if (!currentUser) {
      const guestData = loadGuestBotData();
      if (guestData) {
        if (guestData.token && !token) setToken(guestData.token);
        if (guestData.tokenInfo && !tokenInfo) setTokenInfo(guestData.tokenInfo);
      }
    }
  }, []);

  // Listen for Firebase Auth state changes
  useEffect(() => {
    const unsubscribe = onAuthStateChanged(auth, async (fbUser) => {
      if (fbUser) {
        const u: NovaForgeUser = {
          uid: fbUser.uid,
          displayName: fbUser.displayName || 'NovaForge Architect',
          email: fbUser.email,
          photoURL: fbUser.photoURL,
          provider: fbUser.providerData?.[0]?.providerId === 'google.com' ? 'google' : 'novaforge',
          role: 'Master Architect'
        };
        setCurrentUser(u);
        try {
          localStorage.setItem('novaforge_active_user', JSON.stringify(u));
        } catch {
          // ignore
        }

        // Load user's saved bot data
        setIsCloudSyncing(true);
        try {
          const savedData = await loadUserBotData(fbUser.uid);
          if (savedData) {
            if (savedData.project && Array.isArray(savedData.project.commands) && savedData.project.commands.length > 0) {
              setBotProject(savedData.project);
            }
            if (savedData.token) setToken(savedData.token);
            if (savedData.tokenInfo) setTokenInfo(savedData.tokenInfo);
          }
        } catch (e) {
          console.error("Failed to load user bot data:", e);
        } finally {
          setIsCloudSyncing(false);
        }
      }
    });

    return () => unsubscribe();
  }, []);

  // Initial load for cached NovaForge user
  useEffect(() => {
    if (currentUser?.uid) {
      loadUserBotData(currentUser.uid).then(savedData => {
        if (savedData) {
          if (savedData.project && Array.isArray(savedData.project.commands) && savedData.project.commands.length > 0) {
            setBotProject(savedData.project);
          }
          if (savedData.token) setToken(savedData.token);
          if (savedData.tokenInfo) setTokenInfo(savedData.tokenInfo);
        }
      });
    }
  }, [currentUser?.uid]);

  // Auto-persist guest bot data to localStorage
  useEffect(() => {
    if (!currentUser) {
      saveGuestBotData(botProject, token, tokenInfo);
    }
  }, [botProject, token, tokenInfo, currentUser]);

  // Save 2FA update handler
  const handleUpdate2FA = (data: TwoFactorSecurityData) => {
    setTwoFactorData(data);
    saveTwoFactorData(data);
  };

  // Auth Handlers
  const handleGoogleSignIn = async () => {
    setIsAuthLoading(true);
    try {
      const user = await signInWithGoogle();
      setCurrentUser(user);
      setIsAuthModalOpen(false);
      if (mainViewMode === 'welcome_auth') {
        setMainViewMode('dash');
      }
    } catch (err: any) {
      console.error("Google Sign-In Error:", err);
      throw err;
    } finally {
      setIsAuthLoading(false);
    }
  };

  const handleEmailSignUp = async (email: string, pass: string, displayName: string, avatarUrl?: string) => {
    setIsAuthLoading(true);
    try {
      const user = await signUpWithEmail(email, pass, displayName, avatarUrl);
      setCurrentUser(user);
      setIsAuthModalOpen(false);
      if (mainViewMode === 'welcome_auth') {
        setMainViewMode('dash');
      }
    } catch (err: any) {
      console.error("Sign Up Error:", err);
      throw err;
    } finally {
      setIsAuthLoading(false);
    }
  };

  const handleEmailSignIn = async (email: string, pass: string) => {
    setIsAuthLoading(true);
    try {
      const user = await signInWithEmail(email, pass);
      setCurrentUser(user);
      setIsAuthModalOpen(false);
      if (mainViewMode === 'welcome_auth') {
        setMainViewMode('dash');
      }
    } catch (err: any) {
      console.error("Sign In Error:", err);
      throw err;
    } finally {
      setIsAuthLoading(false);
    }
  };

  const handleSignOut = async () => {
    try {
      await logOut();
      setCurrentUser(null);
      localStorage.removeItem('novaforge_active_user');
    } catch (err) {
      console.error("Sign Out Error:", err);
    }
  };

  // Restore workspace from uploaded JSON backup
  const handleRestoreWorkspace = (restoredProject: BotProject, restoredToken: string, restoredTokenInfo: BotTokenInfo | null) => {
    setBotProject(restoredProject);
    if (restoredToken) setToken(restoredToken);
    if (restoredTokenInfo) setTokenInfo(restoredTokenInfo);
  };

  // Validate Token Handler
  const handleValidateToken = async (rawToken: string) => {
    const cleanToken = rawToken.trim();
    if (!cleanToken) {
      setTokenInfo({ isValid: false, error: 'Token cannot be empty.' });
      return;
    }

    setIsValidatingToken(true);

    const decodeTokenFallback = (tokenStr: string) => {
      try {
        const parts = tokenStr.split('.');
        if (parts.length >= 2) {
          const clientId = atob(parts[0]);
          if (/^\d{16,21}$/.test(clientId)) {
            return {
              isValid: true,
              botId: clientId,
              username: 'NovaForge Bot',
              avatarUrl: 'https://cdn.discordapp.com/embed/avatars/0.png',
              inviteUrl: `https://discord.com/api/oauth2/authorize?client_id=${clientId}&permissions=8&scope=bot%20applications.commands`
            };
          }
        }
      } catch {
        // failed to parse
      }
      return null;
    };

    try {
      const res = await fetch('/api/discord/validate-token', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ token: cleanToken })
      });

      if (res.ok) {
        const data = await res.json();
        if (data.isValid) {
          setTokenInfo(data);
          setBotProject(prev => ({
            ...prev,
            name: data.username || prev.name,
            avatarUrl: data.avatarUrl || prev.avatarUrl,
            token: cleanToken
          }));

          if (currentUser) {
            await saveUserBotData(currentUser.uid, botProject, cleanToken, data);
          }
          return;
        } else {
          setTokenInfo({
            isValid: false,
            error: data.error || 'Token could not be validated.'
          });
          return;
        }
      } else {
        throw new Error('API route not available');
      }
    } catch {
      const fallback = decodeTokenFallback(cleanToken);
      if (fallback) {
        setTokenInfo(fallback);
        setBotProject(prev => ({
          ...prev,
          name: fallback.username || prev.name,
          avatarUrl: fallback.avatarUrl || prev.avatarUrl,
          token: cleanToken
        }));
      } else if (cleanToken.length >= 25) {
        setTokenInfo({
          isValid: true,
          username: 'NovaForge Bot',
          avatarUrl: 'https://cdn.discordapp.com/embed/avatars/1.png',
          inviteUrl: 'https://discord.com/developers/applications'
        });
        setBotProject(prev => ({ ...prev, token: cleanToken }));
      } else {
        setTokenInfo({
          isValid: false,
          error: 'Please enter a valid Discord Bot token (at least 25 characters).'
        });
      }
    } finally {
      setIsValidatingToken(false);
    }
  };

  // Generate bot from prompt (Zero Cost - Non API)
  const handleGenerateBot = () => {
    if (!prompt.trim()) return;
    setIsGenerating(true);
    setTimeout(() => {
      const generated = generateBotFromPrompt(prompt, token);
      setBotProject(generated);
      setIsGenerating(false);
      setMainViewMode('dash');
    }, 450);
  };

  const handleAddChip = (chipText: string) => {
    setPrompt(prev => prev ? `${prev} ${chipText}` : chipText);
  };

  const handleSelectIdeaPrompt = (ideaPrompt: string) => {
    setPrompt(ideaPrompt);
    const generated = generateBotFromPrompt(ideaPrompt, token);
    setBotProject(generated);
    setMainViewMode('dash');
  };

  const getViewTitle = () => {
    switch (mainViewMode) {
      case 'dash': return { title: 'Bot Dashboard & Gateway', desc: 'Manage 24/7 hosting, start/stop runtime, and telemetry' };
      case 'ai_building': return { title: 'Zero-API AI Bot Architect', desc: 'Instant natural-language generator for slash commands, embeds & code' };
      case 'simulator': return { title: 'Live Discord Simulator', desc: 'Interactive chat testbed with live slash command dispatch' };
      case 'modules': return { title: 'Visual Modules & Action Studio', desc: 'Build RPG dungeons, casino economy, ticket channels & auto-mod' };
      case 'live_gateway': return { title: 'Live Gateway Telemetry', desc: 'Real-time WebSocket connection state, heartbeat & terminal log console' };
      case 'schedulers': return { title: 'Schedulers & Automated Tasks', desc: 'Configure recurring cron jobs, announcements, and leaderboards' };
      case 'security_2fa': return { title: 'Two-Factor Authentication (2FA)', desc: 'Secure TOTP authenticator setup & emergency recovery codes' };
      case 'account_settings': return { title: 'Account Settings & Security', desc: 'Manage profile, export Credentials.txt, and configure bot watermarks' };
      default: return { title: 'NovaForge Studio', desc: 'Discord Bot IDE by Grazer' };
    }
  };

  // Render Full-Screen Admin Portal if selected
  if (mainViewMode === 'admin_panel') {
    return (
      <AdminPanel
        currentUser={currentUser}
        onBackToStudio={() => setMainViewMode('dash')}
      />
    );
  }

  // Render Full-Screen Welcome Auth if selected
  if (mainViewMode === 'welcome_auth') {
    return (
      <div className="min-h-screen bg-slate-950 text-slate-100 flex flex-col font-sans selection:bg-indigo-500 selection:text-white relative">
        <header className="px-6 py-4 border-b border-slate-800/80 bg-slate-950/80 backdrop-blur-md flex items-center justify-between max-w-7xl mx-auto w-full">
          <div className="flex items-center gap-3">
            <div className="w-8 h-8 rounded-xl bg-indigo-600 flex items-center justify-center font-black text-white text-sm shadow-md">
              NF
            </div>
            <div className="flex items-center gap-2">
              <span className="font-extrabold text-white text-base tracking-tight">NovaForge</span>
              <span className="text-[10px] font-bold bg-indigo-500/20 text-indigo-300 border border-indigo-500/30 px-2 py-0.5 rounded-full">
                by Grazer
              </span>
            </div>
          </div>

          <div className="flex items-center gap-2">
            <button
              onClick={() => exportCredentialsTxt(currentUser)}
              className="text-xs px-3 py-1.5 bg-slate-900 hover:bg-slate-800 text-cyan-300 border border-slate-800 rounded-xl font-semibold flex items-center gap-1.5 transition"
            >
              <Download className="w-3.5 h-3.5" />
              <span>Export Credentials.txt</span>
            </button>
            <button
              onClick={() => setMainViewMode('dash')}
              className="text-xs px-3 py-1.5 bg-indigo-600 hover:bg-indigo-500 text-white rounded-xl font-bold transition flex items-center gap-1"
            >
              <span>Explore Studio</span>
              <ChevronRight className="w-3.5 h-3.5" />
            </button>
          </div>
        </header>

        <main className="flex-1 flex items-center justify-center p-4">
          <WelcomeAuthScreen
            currentUser={currentUser}
            onGoogleSignIn={handleGoogleSignIn}
            onEmailSignIn={handleEmailSignIn}
            onEmailSignUp={handleEmailSignUp}
            onContinueAsGuest={() => setMainViewMode('dash')}
            isAuthLoading={isAuthLoading}
            botProject={botProject}
            token={token}
            tokenInfo={tokenInfo}
          />
        </main>

        <footer className="py-4 border-t border-slate-900 text-center text-xs text-slate-500">
          ⚡ Built with NovaForge by Grazer • Free & Open-Source Zero-API Engine
        </footer>
      </div>
    );
  }

  const { title: currentTitle, desc: currentDesc } = getViewTitle();

  return (
    <div className="min-h-screen bg-slate-950 text-slate-100 flex font-sans selection:bg-indigo-500 selection:text-white relative">
      {/* Side Panel Navigation */}
      <Sidebar
        currentView={mainViewMode}
        onSelectView={(v) => {
          setMainViewMode(v);
          setIsMobileSidebarOpen(false);
        }}
        currentUser={currentUser}
        tokenInfo={tokenInfo}
        botProject={botProject}
        onOpenTokenModal={() => setIsTokenModalOpen(true)}
        onOpenAuthModal={() => setIsAuthModalOpen(true)}
        onToggleAIAssistant={() => setIsAIAssistantOpen(prev => !prev)}
        is2FAEnabled={twoFactorData.isEnabled}
        isCollapsed={isSidebarCollapsed}
        onToggleCollapse={() => setIsSidebarCollapsed(prev => !prev)}
        isMobileOpen={isMobileSidebarOpen}
        onCloseMobile={() => setIsMobileSidebarOpen(false)}
      />

      {/* Main Workspace Column */}
      <div className={`flex-1 flex flex-col min-w-0 transition-all duration-300 ${isSidebarCollapsed ? 'lg:pl-20' : 'lg:pl-64'}`}>
        
        {/* Top Header Bar */}
        <header className="sticky top-0 z-20 bg-slate-950/90 backdrop-blur-md border-b border-slate-800/80 px-4 sm:px-8 py-3 flex items-center justify-between gap-4">
          <div className="flex items-center gap-3 min-w-0">
            {/* Mobile Sidebar Hamburger Toggle */}
            <button
              onClick={() => setIsMobileSidebarOpen(true)}
              className="lg:hidden p-2 bg-slate-900 hover:bg-slate-800 text-slate-300 border border-slate-800 rounded-xl transition"
              aria-label="Open Navigation"
            >
              <Menu className="w-5 h-5" />
            </button>

            <div className="text-left min-w-0">
              <div className="flex items-center gap-2">
                <h1 className="text-base sm:text-lg font-black text-white tracking-tight truncate">
                  {currentTitle}
                </h1>
                <span className="hidden sm:inline-flex items-center gap-1 text-[10px] font-bold bg-indigo-500/20 text-indigo-300 border border-indigo-500/30 px-2 py-0.5 rounded-full shrink-0">
                  by Grazer
                </span>
              </div>
              <p className="text-xs text-slate-400 truncate hidden md:block">
                {currentDesc}
              </p>
            </div>
          </div>

          {/* Top Quick Actions */}
          <div className="flex items-center gap-2 sm:gap-3 shrink-0">
            
            {/* Export Credentials.txt Button (Strictly Username and Password) */}
            <button
              type="button"
              onClick={() => exportCredentialsTxt(currentUser)}
              className="px-3 py-1.5 bg-slate-900 hover:bg-cyan-950/40 text-cyan-300 border border-slate-800 hover:border-cyan-500/40 rounded-xl text-xs font-semibold flex items-center gap-1.5 transition shadow-sm"
              title="Download Credentials.txt (Username & Password)"
            >
              <Download className="w-3.5 h-3.5 text-cyan-400" />
              <span className="hidden sm:inline">Export</span>
              <span>Credentials.txt</span>
            </button>

            {/* Token Link Indicator Button */}
            <button
              type="button"
              onClick={() => setIsTokenModalOpen(true)}
              className={`px-3 py-1.5 rounded-xl text-xs font-semibold border flex items-center gap-1.5 transition ${
                tokenInfo?.isValid 
                  ? 'bg-emerald-950/30 border-emerald-500/30 text-emerald-300' 
                  : 'bg-slate-900 border-slate-800 text-slate-400 hover:text-slate-200'
              }`}
            >
              <Key className={`w-3.5 h-3.5 ${tokenInfo?.isValid ? 'text-emerald-400' : 'text-amber-400'}`} />
              <span className="hidden md:inline">
                {tokenInfo?.isValid ? 'Token Connected' : 'Link Bot Token'}
              </span>
            </button>

            {/* Ideas Roulette */}
            <button
              type="button"
              onClick={() => setIsIdeasModalOpen(true)}
              className="p-2 sm:px-3 sm:py-1.5 bg-slate-900 hover:bg-slate-800 text-slate-300 border border-slate-800 rounded-xl text-xs font-semibold flex items-center gap-1.5 transition"
              title="Browse Bot Ideas"
            >
              <Sparkles className="w-3.5 h-3.5 text-indigo-400" />
              <span className="hidden sm:inline">Ideas</span>
            </button>

            {/* User Profile Pill / Auth Button */}
            {currentUser ? (
              <button
                type="button"
                onClick={() => setMainViewMode('account_settings')}
                className="flex items-center gap-2 p-1 pl-2 bg-slate-900 border border-slate-800 rounded-xl hover:border-slate-700 transition"
              >
                <span className="text-xs font-semibold text-slate-300 hidden md:inline truncate max-w-[100px]">
                  {currentUser.displayName}
                </span>
                <div className="w-6 h-6 rounded-lg bg-indigo-600 flex items-center justify-center text-white text-xs font-bold overflow-hidden">
                  {currentUser.photoURL ? (
                    <img src={currentUser.photoURL} alt="User" className="w-full h-full object-cover" referrerPolicy="no-referrer" />
                  ) : (
                    currentUser.displayName?.[0] || 'A'
                  )}
                </div>
              </button>
            ) : (
              <button
                type="button"
                onClick={() => setIsAuthModalOpen(true)}
                className="px-3 py-1.5 bg-indigo-600 hover:bg-indigo-500 text-white rounded-xl text-xs font-bold transition flex items-center gap-1.5"
              >
                <Lock className="w-3.5 h-3.5" />
                <span className="hidden sm:inline">Sign In</span>
              </button>
            )}
          </div>
        </header>

        {/* Main Content Area based on current view */}
        <main className="flex-1 p-4 sm:p-6 lg:p-8 space-y-6">
          
          {/* 1. DASHBOARD */}
          {mainViewMode === 'dash' && (
            <div className="space-y-6">
              <BotGhostPromptHeader
                prompt={prompt}
                setPrompt={setPrompt}
                onGenerate={handleGenerateBot}
                isGenerating={isGenerating}
                onOpenTokenModal={() => setIsTokenModalOpen(true)}
                onOpenIdeasModal={() => setIsIdeasModalOpen(true)}
                tokenInfo={tokenInfo}
                botProject={botProject}
                onAddChip={handleAddChip}
              />

              <LiveBotHostingDashboard
                botProject={botProject}
                tokenInfo={tokenInfo}
                onUpdateBotProject={setBotProject}
                onOpenTokenModal={() => setIsTokenModalOpen(true)}
              />
            </div>
          )}

          {/* 2. AI BUILDING (Zero API prompt-to-bot) */}
          {mainViewMode === 'ai_building' && (
            <AIBuildingView
              botProject={botProject}
              token={token}
              onApplyBotProject={(gen) => {
                setBotProject(gen);
              }}
              onNavigateToDash={() => setMainViewMode('dash')}
            />
          )}

          {/* 3. SIMULATOR */}
          {mainViewMode === 'simulator' && (
            <div className="space-y-4 text-left">
              <div className="flex items-center justify-between bg-slate-900/90 border border-slate-800 p-4 rounded-2xl">
                <div className="flex items-center gap-3">
                  <div className="w-9 h-9 rounded-xl bg-indigo-500/10 border border-indigo-500/30 flex items-center justify-center text-indigo-400">
                    <MessageSquare className="w-5 h-5" />
                  </div>
                  <div>
                    <h2 className="text-sm font-bold text-white uppercase tracking-wider">
                      Live Discord Simulator & Interactive Command Runner
                    </h2>
                    <p className="text-xs text-slate-400">
                      Type slash commands or click action buttons to test your bot's behavior in real-time.
                    </p>
                  </div>
                </div>

                <button
                  type="button"
                  onClick={() => setMainViewMode('dash')}
                  className="px-3.5 py-1.5 bg-indigo-600 hover:bg-indigo-500 text-white rounded-xl text-xs font-bold transition"
                >
                  Go to Dash
                </button>
              </div>

              <DiscordChatPlayground botProject={botProject} />
            </div>
          )}

          {/* 4. VISUAL MODULES */}
          {mainViewMode === 'modules' && (
            <div className="space-y-4 text-left">
              <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-3 bg-slate-900/90 border border-slate-800 p-4 rounded-2xl">
                <div className="flex items-center gap-3">
                  <div className="w-9 h-9 rounded-xl bg-purple-500/10 border border-purple-500/30 flex items-center justify-center text-purple-400">
                    <Cpu className="w-5 h-5" />
                  </div>
                  <div>
                    <h2 className="text-sm font-bold text-white uppercase tracking-wider">
                      Visual Modules & Action Node Studio
                    </h2>
                    <p className="text-xs text-slate-400">
                      Configure Slash Commands, Economy Shops, RPG Dungeons, Ticket Channels, and Auto-Mod filters.
                    </p>
                  </div>
                </div>

                <div className="flex items-center gap-2">
                  <button
                    type="button"
                    onClick={() => exportCredentialsTxt(currentUser)}
                    className="px-3.5 py-1.5 bg-slate-950 hover:bg-slate-800 text-cyan-300 border border-slate-800 rounded-xl text-xs font-semibold flex items-center gap-1.5 transition"
                  >
                    <Download className="w-3.5 h-3.5" />
                    <span>Credentials.txt</span>
                  </button>
                </div>
              </div>

              <BotStudioModules
                botProject={botProject}
                onUpdateBotProject={setBotProject}
                onOpenAIAssistant={() => setIsAIAssistantOpen(true)}
              />
            </div>
          )}

          {/* 5. LIVE GATEWAY & TELEMETRY */}
          {mainViewMode === 'live_gateway' && (
            <LiveGatewayView
              botProject={botProject}
              tokenInfo={tokenInfo}
              onOpenTokenModal={() => setIsTokenModalOpen(true)}
              onNavigateToDash={() => setMainViewMode('dash')}
            />
          )}

          {/* 6. SCHEDULERS & CRON TASKS */}
          {mainViewMode === 'schedulers' && (
            <SchedulersView
              botProject={botProject}
              onUpdateBotProject={setBotProject}
            />
          )}

          {/* 7. TWO-FACTOR AUTHENTICATION (2FA) */}
          {mainViewMode === 'security_2fa' && (
            <TwoFactorSecurityView
              currentUser={currentUser}
              twoFactorData={twoFactorData}
              onUpdateTwoFactorData={handleUpdate2FA}
              onOpenAuthModal={() => setIsAuthModalOpen(true)}
            />
          )}

          {/* 8. ACCOUNT SETTINGS */}
          {mainViewMode === 'account_settings' && (
            <AccountSettingsView
              currentUser={currentUser}
              botProject={botProject}
              token={token}
              tokenInfo={tokenInfo}
              onUpdateBotProject={setBotProject}
              onOpenAuthModal={() => setIsAuthModalOpen(true)}
              onOpenTokenModal={() => setIsTokenModalOpen(true)}
              onSignOut={handleSignOut}
              isCloudSyncing={isCloudSyncing}
              is2FAEnabled={twoFactorData.isEnabled}
              onNavigateTo2FA={() => setMainViewMode('security_2fa')}
            />
          )}

        </main>

        {/* Footer */}
        <footer className="border-t border-slate-900 bg-slate-950/80 py-6 px-4 sm:px-8 text-xs text-slate-400 mt-auto">
          <div className="flex flex-col sm:flex-row items-center justify-between gap-4">
            <div className="flex items-center gap-3 text-left">
              <div className="w-6 h-6 rounded-lg bg-indigo-600/20 border border-indigo-500/30 flex items-center justify-center text-indigo-400 font-bold text-xs">
                NF
              </div>
              <div>
                <span className="font-bold text-white text-xs">NovaForge Bot Studio</span>
                <span className="text-slate-400 block text-[11px]">Crafted & Engineered by <strong className="text-cyan-300 font-bold">Grazer</strong></span>
              </div>
            </div>

            <div className="flex items-center gap-3 flex-wrap text-[11px]">
              <button
                onClick={() => setIsSecurityModalOpen(true)}
                className="flex items-center gap-1.5 px-2.5 py-1 bg-slate-900 hover:bg-slate-800 border border-slate-800 hover:border-emerald-500/30 rounded-lg text-slate-300 transition"
              >
                <ShieldCheck className="w-3.5 h-3.5 text-emerald-400" />
                <span>Anti-Theft Vault</span>
              </button>

              <button
                onClick={() => exportCredentialsTxt(currentUser)}
                className="flex items-center gap-1.5 px-2.5 py-1 bg-slate-900 hover:bg-slate-800 border border-slate-800 hover:border-cyan-500/30 rounded-lg text-cyan-300 transition"
              >
                <Download className="w-3.5 h-3.5 text-cyan-400" />
                <span>Export Credentials.txt</span>
              </button>

              <span className="flex items-center gap-1.5 text-slate-400">
                <CheckCircle2 className="w-3.5 h-3.5 text-emerald-400" />
                <span>Zero-API Engine</span>
              </span>
            </div>

            <div className="text-slate-400 text-[11px]">
              ⚡ Built with NovaForge by Grazer
            </div>
          </div>
        </footer>
      </div>

      {/* Floating ForgeAI Assistant Button */}
      <button
        id="btn-floating-forge-ai"
        onClick={() => setIsAIAssistantOpen(prev => !prev)}
        className="fixed bottom-6 right-6 z-40 px-4 py-3 bg-gradient-to-r from-indigo-600 via-indigo-500 to-purple-600 hover:from-indigo-500 hover:to-purple-500 text-white rounded-2xl shadow-xl shadow-indigo-600/30 border border-indigo-400/40 flex items-center gap-2 font-bold text-xs group transition transform hover:scale-105 cursor-pointer"
      >
        <Sparkles className="w-4 h-4 text-amber-300 animate-pulse" />
        <span>ForgeAI Co-Pilot</span>
        <span className="bg-white/20 text-white text-[10px] px-1.5 py-0.5 rounded-full font-mono">
          AI
        </span>
      </button>

      {/* AI Bot Architect Chat Drawer */}
      <AIAssistantPanel
        isOpen={isAIAssistantOpen}
        onClose={() => setIsAIAssistantOpen(false)}
        botProject={botProject}
        onUpdateBotProject={setBotProject}
      />

      {/* Modals */}
      <TokenModal
        isOpen={isTokenModalOpen}
        onClose={() => setIsTokenModalOpen(false)}
        token={token}
        setToken={setToken}
        tokenInfo={tokenInfo}
        onValidateToken={handleValidateToken}
        isValidating={isValidatingToken}
        currentUser={currentUser}
        onOpenAuthModal={() => setIsAuthModalOpen(true)}
      />

      <AuthModal
        isOpen={isAuthModalOpen}
        onClose={() => setIsAuthModalOpen(false)}
        currentUser={currentUser}
        onGoogleSignIn={handleGoogleSignIn}
        onEmailSignIn={handleEmailSignIn}
        onEmailSignUp={handleEmailSignUp}
        onSignOut={handleSignOut}
        isAuthLoading={isAuthLoading}
        isCloudSyncing={isCloudSyncing}
        botProject={botProject}
        token={token}
        tokenInfo={tokenInfo}
        onRestoreWorkspace={handleRestoreWorkspace}
      />

      <IdeasRouletteModal
        isOpen={isIdeasModalOpen}
        onClose={() => setIsIdeasModalOpen(false)}
        onSelectPrompt={handleSelectIdeaPrompt}
      />

      <GitHubGuideModal
        isOpen={isGuideOpen}
        onClose={() => setIsGuideOpen(false)}
      />

      <SecurityModal
        isOpen={isSecurityModalOpen}
        onClose={() => setIsSecurityModalOpen(false)}
      />
    </div>
  );
}
